@hostname=http://192.168.1.3:4000
@token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiYWRtaW4iOnRydWUsImlhdCI6MTUxNjIzOTAyMn0.KMUFsIDTnFmyG3nMiGM6H9FNFUROf3wh7SmqJp-QV30
###
POST {{hostname}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

mutation {
  runScraper {
    msg
  }
}
###
POST {{hostname}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query ($id: ID!) {
  character(id: $id) {
    _id
    name
    description
    link
    appareance
    year
  }
}

{
    "id": "68c0dd0fe828c7351e58aa42"
}

###
POST {{hostname}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query ($name: String!) {
  characters(name: $name) {
    _id
    name
    description
    link
    appareance
    year
  }
}

{
    "name": "Akudai"
}

###
POST {{hostname}}/graphql
Content-Type: application/json
Authorization: Bearer {{token}}
X-REQUEST-TYPE: GraphQL

query ($year: Int!) {
  characters(year: $year) {
    _id
    name
    description
    link
    appareance
    year
  }
}

{
    "year": 2009
}
