POST http://192.168.56.20:4000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

query ($id: ID!) {
  user(id: $id) {
    name
    id
  }
}

{
    "id": "1"
}
###

POST http://192.168.56.20:4000/graphql
Content-Type: application/json
Authorization: Bearer xxx
X-REQUEST-TYPE: GraphQL

mutation {
  runScraper {
    msg
  }
}
